services:

  datomic-transactor:
    build: datomic-database/docker/transactor
    environment:
      BOOT_CONFIG_EDN: /usr/config/dev/config.edn
    volumes:
      - ./datomic-database/config:/usr/config
    ports:
      - '4334:4334'

  datomic-console:
    build: datomic-database/docker/console
    links:
      - datomic-transactor
    environment:
      DB_URI: datomic:dev://datomic-transactor:4334/?password=unsafe
    ports:
      - '8080:8080'

  server-app:
    build: clojure-api
    links:
      - datomic-transactor
    environment:
      DATOMIC_URL: datomic:dev://datomic-transactor:4334/product/?password=unsafe
    ports:
      - "8888:9000"

  datomic-tools:
    build: datomic-database/docker/tools
    links:
      - datomic-transactor
