services:

  datomic-transactor:
    build: datomic-database/docker/transactor
    environment:
      BOOT_CONFIG_EDN: /usr/config/dev/config.edn
    volumes:
      - ./datomic-database/config:/usr/config
    ports:
      - '4334:4334'

  datomic-console:
    build: datomic-database/docker/console
    links:
      - datomic-transactor
    environment:
      DB_URI: datomic:dev://datomic-transactor:4334/?password=unsafe
    ports:
      - '9091:8080'

  clojure-api:
    build: clojure-api
    links:
      - prometheus
      - datomic-transactor
      - kafka
    environment:
      DATOMIC_URL: datomic:dev://datomic-transactor:4334/product/?password=unsafe
      BOOTSTRAP_SERVER: kafka:9092
    ports:
      - "9000:9000"
    depends_on:
      - kafka
      - prometheus

  clojure-async:
    build: clojure-async
    links:
      - kafka
    environment:
      BOOTSTRAP_SERVER: kafka:9092
    ports:
      - "9001:9001"
    depends_on:
      - kafka

  datomic-tools:
    build: datomic-database/docker/tools
    links:
      - datomic-transactor

#  jmx-kafka:
#    image: "sscaling/jmx-prometheus-exporter"
#    ports:
#      - "5556:5556"
#    environment:
#      CONFIG_YML: "/etc/jmx_exporter/config.yml"
#    volumes:
#      - ./etc/jmx_exporter/config_kafka.yml:/etc/jmx_exporter/config.yml
#    container_name: jmx-kafka
#    depends_on:
#      - kafka

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_JMX_PORT: 9991
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=DEBUG"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "9099:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=clojure-kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  prometheus:
    image: prom/prometheus:v2.4.0
    volumes:
      - ./prometheus/config:/etc/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.5.12
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    env_file:
      - ./grafana/environment
    environment:
      GF_PATHS_DATA: /var/lib/grafana
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus

  kafka-exporter:
    container_name: kafka-exporter
    image: bitnami/kafka-exporter:1.7.0
    command:
      - "--kafka.server=kafka:9092"
    ports:
      - 9308:9308

  jmx-exporter-broker:
    container_name: jmx-exporter-broker
    image: bitnami/jmx-exporter:0.20.0
    volumes:
      - ./exporter/exporter-brokers.yml:/opt/bitnami/jmx-exporter/exporter.yml
    command:
      - "5556"
      - exporter.yml
    ports:
      - 5556:5556