services:
  datomicdb:
    build: my-datomic-dockerized/datomic-db
    environment:
      - ADMIN_PASSWORD=admin
      - DATOMIC_PASSWORD=datomic
    ports:
      - "4336:4336"
      - "4335:4335"
      - "4334:4334"
    volumes:
      - "/data"
  datomic-console:
    build: my-datomic-dockerized/datomic-console
    environment:
      - ADMIN_PASSWORD=admin
      - DATOMIC_PASSWORD=datomic
    ports:
      - "8080:8080"
    links:
      - datomicdb
  server-app:
    build: clojure-simple-http
    ports:
      - "8888:8080"