services:

  datomic-transactor:
    build: datomic-database/docker/transactor
    environment:
      BOOT_CONFIG_EDN: /usr/config/dev/config.edn
    volumes:
      - ./datomic-database/config:/usr/config
    ports:
      - '4334:4334'

  datomic-console:
    build: datomic-database/docker/console
    links:
      - datomic-transactor
    environment:
      DB_URI: datomic:dev://datomic-transactor:4334/?password=unsafe
    ports:
      - '9090:8080'

  clojure-api:
    build: clojure-api
    links:
      - datomic-transactor
      - kafka
    environment:
      DATOMIC_URL: datomic:dev://datomic-transactor:4334/product/?password=unsafe
      BOOTSTRAP_SERVER: kafka:9092
    ports:
      - "9000:9000"
    depends_on:
      - kafka

  clojure-async:
    build: clojure-async
    links:
      - kafka
    environment:
      BOOTSTRAP_SERVER: kafka:9092
    ports:
      - "9001:9001"
    depends_on:
      - kafka

  datomic-tools:
    build: datomic-database/docker/tools
    links:
      - datomic-transactor

  kafka:
    image: bitnami/kafka:latest
    restart: on-failure
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NUM_PARTITIONS=3
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "9091:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=clojure-kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

volumes:
  conduktor_data: {}
