scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets: ['grafana:3000']
  - job_name: 'clojure-api'
    scrape_interval: 5s
    static_configs:
    - targets: ['clojure-api:9000']
  - job_name: 'kafka-cluster'
    static_configs:
      - targets: ['jmx-kafka-cluster:5566']
  - job_name: "kafka"
    scrape_interval: 1s
    static_configs:
      - targets:
        - jmx-exporter-broker:5556
        - kafka-exporter:9308