services:

  datomic-transactor:
    build: ./docker/transactor
    environment:
      BOOT_CONFIG_EDN: /usr/config/dev/config.edn
    volumes:
      - ./config:/usr/config
    ports:
      - '4334:4334'

  datomic-console:
    build: ./docker/console
    links:
      - datomic-transactor
    environment:
      DB_URI: datomic:dev://datomic-transactor:4334/?password=unsafe
    ports:
      - '8080:8080'

  server-app:
    build: ../clojure-simple-http
    ports:
      - "8888:8080"
    links:
      - datomic-transactor

  datomic-tools:
    build: ./docker/tools
    links:
      - datomic-transactor
