services:

  datomic-storage:
    image: postgres:16.1-bookworm
    environment:
      POSTGRES_DB: my-datomic
      POSTGRES_USER: datomic-user
      POSTGRES_PASSWORD: unsafe
    ports:
      - '5432:5432'

  datomic-transactor:
    build: ./docker/transactor
    environment:
      BOOT_CONFIG_EDN: /usr/config/postgresql/config.edn
    volumes:
      - ./config:/usr/config
    ports:
      - '4334:4334'

  datomic-console:
    build: ./docker/console
    links:
      - datomic-storage
    environment:
      DB_URI: datomic:sql://?jdbc:postgresql://datomic-storage:5432/my-datomic?user=datomic-user&password=unsafe
    ports:
      - '8080:8080'

  datomic-tools:
    build: ./docker/tools
    links:
      - datomic-storage
